name: deploy

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '12 8 * * 1' # 09:12 every monday



jobs:
  check-commits:
    runs-on: self-hosted
    steps:
      - name: Get new commits
        run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_ENV

  stop-bot:
    needs: check-commits
    runs-on: self-hosted
    if: ${{ vars.NEW_COMMIT_COUNT > 0 }}
    steps:
      - name: Stop bot service
        run: sudo systemctl stop game-streams

  build:
    needs: stop-bot
    runs-on: self-hosted
    if: ${{ vars.NEW_COMMIT_COUNT > 0 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Set CGO
        run: go env -w CGO_ENABLED=1

      - name: Install dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Vet
        run: go vet game-streams/main.go

      - name: Build
        run: go build -v -o bin/game-streams game-streams/main.go

  start-bot:
    needs: build
    runs-on: self-hosted
    if: ${{ vars.NEW_COMMIT_COUNT > 0 }}
    steps:
      - name: Start bot service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl start game-streams
