name: deploy

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '18 5 * * 1' # 05:18 every monday

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  check-commits:
    needs: checkout
    runs-on: self-hosted
    outputs:
          new_commits: ${{ steps.get-commits.outputs.week_commit_count }}
    steps:
      - name: Get new commits
        id: get-commits
        run: echo "week_commit_count=$(git log --oneline --since '1 week ago' | wc -l)" >> $GITHUB_OUTPUT

  stop-bot:
    needs: check-commits
    runs-on: self-hosted
    if: ${{ needs.check-commits.outputs.new_commits > 0 }}
    steps:
      - name: Stop bot service
        run: sudo systemctl stop game-streams

  build:
    needs: stop-bot
    runs-on: self-hosted

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Set CGO
        run: go env -w CGO_ENABLED=1

      - name: Install dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Vet
        run: go vet game-streams/main.go

      - name: Build
        run: go build -v -o bin/game-streams game-streams/main.go

  start-bot:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Start bot service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl start game-streams
