name: main

on:
  push:
    branches:
      - "main"

jobs:
  stopbot:
    runs-on: self-hosted
    steps:
      - name: Stop bot service
        run: sudo systemctl stop gamestreambot

  build:
    needs: stopbot
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Set CGO
        run: go env -w CGO_ENABLED=1

      - name: Install dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Vet
        run: go vet gamestreambot/main.go

      - name: Build
        run: go build -v -o bin/gamestreambot gamestreambot/main.go

  #      - name: Test
  #        run: go test -json gamestreambot/main.go > report.json

  #      - name: Upload test results
  #        uses: actions/upload-artifact@v4
  #        with:
  #          name: test-results
  #          path: report.json

  startbot:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Start bot service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl start gamestreambot
