name: main

on:
  push:
    branches:
      - "main"

jobs:
  stopbot:
    runs-on: self-hosted
    steps:
      - name: Stop bot service
        run: sudo systemctl stop game-streams

  build:
    needs: stopbot
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Set CGO
        run: go env -w CGO_ENABLED=1

      - name: Install dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Vet
        run: go vet game-streams/main.go

      - name: Build
        run: go build -v -o bin/game-streams game-streams/main.go

  startbot:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Start bot service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl start game-streams
