name: r2 upload

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '24 5 * * 1' # 05:24 every monday

jobs:
  check-commits:
    runs-on: self-hosted
    outputs:
          new_commits: ${{ steps.get-commits.outputs.week_commit_count }}
    steps:
      - name: Get new commits
        id: get-commits
        run: echo "week_commit_count=$(git log --oneline --since '1 week ago' | wc -l)" >> $GITHUB_OUTPUT

  upload:
    needs: check-commits
    runs-on: self-hosted
    if: ${{ needs.check-commits.outputs.new_commits > 0 }}
    steps:
      - name: R2 upload
        uses: ryand56/r2-upload-action@v1.3
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: assets/web
          destination-dir: ./
